######################################################################
# Automatically generated by qmake (3.0) Sun Mar 12 18:32:16 2017
######################################################################

QT += gui widgets

TEMPLATE = app
TARGET = QPixmap
INCLUDEPATH += .

# Input
HEADERS += pixmap.h
SOURCES += main.cpp pixmap.cpp
