######################################################################
# Automatically generated by qmake (3.0) Mon Feb 27 21:13:09 2017
######################################################################

TEMPLATE = app
TARGET = owner
INCLUDEPATH += .

# Input
SOURCES += owner.cpp
