######################################################################
# Automatically generated by qmake (3.0) Sun Apr 2 20:18:53 2017
######################################################################

QT += gui widgets

TEMPLATE = app
TARGET = lines
INCLUDEPATH += .

# Input
HEADERS += lines.h
SOURCES += lines.cpp main.cpp
