######################################################################
# Automatically generated by qmake (3.0) Mon Feb 27 20:28:42 2017
######################################################################

TEMPLATE = app
TARGET = myvector
INCLUDEPATH += .

# Input
SOURCES += myvector.cpp
