######################################################################
# Automatically generated by qmake (3.0) Mon Feb 27 20:25:23 2017
######################################################################

TEMPLATE = app
TARGET = myqmap
INCLUDEPATH += .

# Input
SOURCES += myqmap.cpp
