######################################################################
# Automatically generated by qmake (3.0) Mon Feb 27 20:48:00 2017
######################################################################

TEMPLATE = app
TARGET = daystofrom
INCLUDEPATH += .

# Input
SOURCES += daystofrom.cpp
