######################################################################
# Automatically generated by qmake (3.0) Sun Apr 2 20:20:47 2017
######################################################################

QT += gui widgets

TEMPLATE = app
TARGET = puff
INCLUDEPATH += .

# Input
HEADERS += puff.h
SOURCES += main.cpp puff.cpp
