######################################################################
# Automatically generated by qmake (3.0) Sun Apr 2 20:22:23 2017
######################################################################

QT += gui widgets

TEMPLATE = app
TARGET = shapes
INCLUDEPATH += .

# Input
HEADERS += shapes.h
SOURCES += main.cpp shapes.cpp
