######################################################################
# Automatically generated by qmake (3.0) Mon Feb 27 21:11:19 2017
######################################################################

TEMPLATE = app
TARGET = file_path
INCLUDEPATH += .

# Input
SOURCES += file_path.cpp
