######################################################################
# Automatically generated by qmake (3.0) Wed Mar 1 19:04:38 2017
######################################################################

QT += gui widgets

TEMPLATE = app
TARGET = nesting_layouts
INCLUDEPATH += .

# Input
HEADERS += nesting.h
SOURCES += main.cpp nesting.cpp
