######################################################################
# Automatically generated by qmake (3.0) Sun Mar 5 13:11:55 2017
######################################################################

QT += gui widgets

TEMPLATE = app
TARGET = click
INCLUDEPATH += .

# Input
HEADERS += click.h
SOURCES += click.cpp main.cpp
