######################################################################
# Automatically generated by qmake (3.0) Mon Feb 27 20:39:25 2017
######################################################################

TEMPLATE = app
TARGET = battles
INCLUDEPATH += .

# Input
SOURCES += battles.cpp
