######################################################################
# Automatically generated by qmake (3.0) Tue Feb 21 21:22:25 2017
######################################################################

TEMPLATE = app
TARGET = basic
INCLUDEPATH += .

# Input
SOURCES += basic.cpp

QT -= gui
