######################################################################
# Automatically generated by qmake (3.0) Sun Mar 12 18:08:39 2017
######################################################################

QT += gui widgets

TEMPLATE = app
TARGET = QSlider
INCLUDEPATH += .

# Input
HEADERS += slider.h
SOURCES += main.cpp slider.cpp
