######################################################################
# Automatically generated by qmake (3.0) Wed Mar 1 18:50:15 2017
######################################################################

QT += gui widgets

TEMPLATE = app
TARGET = absolute
INCLUDEPATH += .

# Input
SOURCES += absolute.cpp
