######################################################################
# Automatically generated by qmake (3.0) Mon Feb 27 20:42:13 2017
######################################################################

TEMPLATE = app
TARGET = customtimeformats
INCLUDEPATH += .

# Input
SOURCES += customtimeformats.cpp
