######################################################################
# Automatically generated by qmake (3.0) Sun Apr 2 20:09:22 2017
######################################################################

QT += gui widgets

TEMPLATE = app
TARGET = snake
INCLUDEPATH += .

# Input
HEADERS += snake.h
SOURCES += main.cpp snake.cpp
