######################################################################
# Automatically generated by qmake (3.0) Mon Feb 27 20:39:55 2017
######################################################################

TEMPLATE = app
TARGET = comparedates
INCLUDEPATH += .

# Input
SOURCES += comparedates.cpp
