######################################################################
# Automatically generated by qmake (3.0) Mon Feb 27 21:03:09 2017
######################################################################

TEMPLATE = app
TARGET = validity
INCLUDEPATH += .

# Input
SOURCES += validity.cpp
