######################################################################
# Automatically generated by qmake (3.0) Tue Feb 21 22:17:18 2017
######################################################################

TEMPLATE = app
TARGET = letters
INCLUDEPATH += .

# Input
SOURCES += letters.cpp
