######################################################################
# Automatically generated by qmake (3.0) Mon Feb 27 20:41:32 2017
######################################################################

TEMPLATE = app
TARGET = customdateformats
INCLUDEPATH += .

# Input
SOURCES += customdateformats.cpp
