######################################################################
# Automatically generated by qmake (3.0) Mon Feb 27 20:59:39 2017
######################################################################

TEMPLATE = app
TARGET = timeformats
INCLUDEPATH += .

# Input
SOURCES += timeformats.cpp
