######################################################################
# Automatically generated by qmake (3.0) Sun Apr 2 20:16:57 2017
######################################################################

QT += gui widgets

TEMPLATE = app
TARGET = donut
INCLUDEPATH += .

# Input
HEADERS += donut.h
SOURCES += donut.cpp main.cpp
