######################################################################
# Automatically generated by qmake (3.0) Wed Mar 1 18:54:18 2017
######################################################################

QT += gui widgets

TEMPLATE = app
TARGET = qvboxlayout
INCLUDEPATH += .

# Input
HEADERS += verticalbox.h
SOURCES += main.cpp verticalbox.cpp
