######################################################################
# Automatically generated by qmake (3.0) Sun Mar 12 18:28:17 2017
######################################################################

QT += gui widgets

TEMPLATE = app
TARGET = QListWidget
INCLUDEPATH += .

# Input
HEADERS += listwidget.h
SOURCES += listwidget.cpp main.cpp
