######################################################################
# Automatically generated by qmake (3.0) Sun Mar 12 18:37:05 2017
######################################################################

QT += gui widgets

TEMPLATE = app
TARGET = QSplitter
INCLUDEPATH += .

# Input
HEADERS += splitter.h
SOURCES += main.cpp splitter.cpp
