######################################################################
# Automatically generated by qmake (3.0) Wed Mar 1 19:07:34 2017
######################################################################

QT += gui widgets

TEMPLATE = app
TARGET = qformlayout
INCLUDEPATH += .

# Input
HEADERS += form.h
SOURCES += form.cpp main.cpp
