######################################################################
# Automatically generated by qmake (3.0) Mon Feb 27 21:11:56 2017
######################################################################

TEMPLATE = app
TARGET = file_size
INCLUDEPATH += .

# Input
SOURCES += file_size.cpp
