######################################################################
# Automatically generated by qmake (3.0) Tue Feb 28 21:18:49 2017
######################################################################

QT += gui widgets

TEMPLATE = app
TARGET = application_skeleton
INCLUDEPATH += .

# Input
HEADERS += skeleton.h
SOURCES += main.cpp skeleton.cpp
