######################################################################
# Automatically generated by qmake (3.0) Mon Feb 27 20:30:16 2017
######################################################################

TEMPLATE = app
TARGET = sortcustomclass
INCLUDEPATH += .

# Input
HEADERS += book.h
SOURCES += book.cpp sortcustomclass.cpp
