######################################################################
# Automatically generated by qmake (3.0) Tue Feb 21 22:09:41 2017
######################################################################

TEMPLATE = app
TARGET = converts
INCLUDEPATH += .

# Input
SOURCES += converts.cpp
