######################################################################
# Automatically generated by qmake (3.0) Mon Feb 27 21:09:49 2017
######################################################################

TEMPLATE = app
TARGET = dirs
INCLUDEPATH += .

# Input
SOURCES += dirs.cpp
