######################################################################
# Automatically generated by qmake (3.0) Tue Feb 21 21:46:07 2017
######################################################################

TEMPLATE = app
TARGET = length
INCLUDEPATH += .

# Input
SOURCES += length.cpp

QT -= gui