######################################################################
# Automatically generated by qmake (3.0) Mon Feb 20 19:39:04 2017
######################################################################

TEMPLATE = app
TARGET = small_gui
INCLUDEPATH += .

# Input
SOURCES += simple.cpp

QT += widgets