######################################################################
# Automatically generated by qmake (3.0) Wed Mar 1 18:56:54 2017
######################################################################

QT += gui widgets

TEMPLATE = app
TARGET = buttons
INCLUDEPATH += .

# Input
HEADERS += buttons.h
SOURCES += buttons.cpp main.cpp
