######################################################################
# Automatically generated by qmake (3.0) Tue Feb 28 20:44:50 2017
######################################################################

QT += gui widgets

TEMPLATE = app
TARGET = simplemenu
INCLUDEPATH += .

# Input
HEADERS += simplemenu.h
SOURCES += main.cpp simplemenu.cpp
