######################################################################
# Automatically generated by qmake (3.0) Sun Apr 2 20:17:55 2017
######################################################################

QT += gui widgets

TEMPLATE = app
TARGET = linear_gradients
INCLUDEPATH += .

# Input
HEADERS += linear_gradients.h
SOURCES += linear_gradients.cpp main.cpp
