######################################################################
# Automatically generated by qmake (3.0) Tue Feb 21 22:23:12 2017
######################################################################

TEMPLATE = app
TARGET = html_escape
INCLUDEPATH += .

# Input
SOURCES += html_escape.cpp
