######################################################################
# Automatically generated by qmake (3.0) Mon Feb 27 20:58:38 2017
######################################################################

TEMPLATE = app
TARGET = nofdays
INCLUDEPATH += .

# Input
SOURCES += nofdays.cpp
