######################################################################
# Automatically generated by qmake (3.0) Wed Mar 1 19:24:56 2017
######################################################################

QT += gui widgets

TEMPLATE = app
TARGET = review
INCLUDEPATH += .

# Input
HEADERS += review.h
SOURCES += main.cpp review.cpp
