######################################################################
# Automatically generated by qmake (3.0) Sun Mar 12 18:05:40 2017
######################################################################

QT += gui widgets

TEMPLATE = app
TARGET = QLineEdit
INCLUDEPATH += .

# Input
HEADERS += ledit.h
SOURCES += ledit.cpp main.cpp
