######################################################################
# Automatically generated by qmake (3.0) Mon Feb 27 21:32:30 2017
######################################################################

QT += gui widgets

TEMPLATE = app
TARGET = icon
INCLUDEPATH += .

# Input
SOURCES += icon.cpp
