######################################################################
# Automatically generated by qmake (3.0) Sun Mar 12 18:13:05 2017
######################################################################

QT += gui widgets

TEMPLATE = app
TARGET = Statusbar
INCLUDEPATH += .

# Input
HEADERS += statusbar.h
SOURCES += main.cpp statusbar.cpp
