######################################################################
# Automatically generated by qmake (3.0) Tue Feb 28 20:53:51 2017
######################################################################

QT += gui widgets

TEMPLATE = app
TARGET = icons_shortcuts_and_separators
INCLUDEPATH += .

# Input
HEADERS += anothermenu.h
SOURCES += anothermenu.cpp main.cpp
