######################################################################
# Automatically generated by qmake (3.0) Mon Feb 27 20:50:19 2017
######################################################################

TEMPLATE = app
TARGET = init
INCLUDEPATH += .

# Input
SOURCES += init.cpp
