######################################################################
# Automatically generated by qmake (3.0) Mon Feb 27 20:27:52 2017
######################################################################

TEMPLATE = app
TARGET = mystringlist
INCLUDEPATH += .

# Input
SOURCES += mystringlist.cpp
