######################################################################
# Automatically generated by qmake (3.0) Mon Feb 27 21:07:57 2017
######################################################################

TEMPLATE = app
TARGET = copy_file
INCLUDEPATH += .

# Input
SOURCES += copy_file.cpp
