######################################################################
# Automatically generated by qmake (3.0) Tue Feb 21 22:06:00 2017
######################################################################

TEMPLATE = app
TARGET = looping
INCLUDEPATH += .

# Input
SOURCES += looping.cpp
