######################################################################
# Automatically generated by qmake (3.0) Mon Feb 27 21:12:50 2017
######################################################################

TEMPLATE = app
TARGET = list_dir
INCLUDEPATH += .

# Input
SOURCES += list_dir.cpp
