######################################################################
# Automatically generated by qmake (3.0) Mon Feb 27 21:19:54 2017
######################################################################

TEMPLATE += app
QT += gui widgets

TARGET = simple
INCLUDEPATH += .

# Input
SOURCES += simple.cpp
