######################################################################
# Automatically generated by qmake (3.0) Mon Feb 27 21:12:26 2017
######################################################################

TEMPLATE = app
TARGET = file_times
INCLUDEPATH += .

# Input
SOURCES += file_times.cpp
