######################################################################
# Automatically generated by qmake (3.0) Mon Feb 27 20:56:07 2017
######################################################################

TEMPLATE = app
TARGET = leapyear
INCLUDEPATH += .

# Input
SOURCES += leapyear.cpp
