######################################################################
# Automatically generated by qmake (3.0) Sun Mar 12 18:11:32 2017
######################################################################

QT += gui widgets

TEMPLATE = app
TARGET = QSpinBox
INCLUDEPATH += .

# Input
HEADERS += spinbox.h
SOURCES += main.cpp spinbox.cpp
