######################################################################
# Automatically generated by qmake (3.0) Sun Apr 2 20:08:00 2017
######################################################################

QT += gui widgets

TEMPLATE = app
TARGET = burning
INCLUDEPATH += .

# Input
HEADERS += burning.h widget.h
SOURCES += burning.cpp main.cpp widget.cpp
