######################################################################
# Automatically generated by qmake (3.0) Mon Feb 27 23:44:28 2017
######################################################################

QT += gui widgets

TEMPLATE = app
TARGET = plusminus
INCLUDEPATH += .

# Input
HEADERS += plusminus.h
SOURCES += main.cpp plusminus.cpp
