######################################################################
# Automatically generated by qmake (3.0) Tue Feb 28 21:10:54 2017
######################################################################

QT += gui widgets

TEMPLATE = app
TARGET = qtoolbar
INCLUDEPATH += .

# Input
HEADERS += toolbar.h
SOURCES += main.cpp toolbar.cpp
