######################################################################
# Automatically generated by qmake (3.0) Mon Feb 27 20:51:04 2017
######################################################################

TEMPLATE = app
TARGET = julianday
INCLUDEPATH += .

# Input
SOURCES += julianday.cpp
