######################################################################
# Automatically generated by qmake (3.0) Wed Mar 1 19:09:49 2017
######################################################################

QT += gui widgets

TEMPLATE = app
TARGET = qgridlayout
INCLUDEPATH += .

# Input
HEADERS += calculator.h
SOURCES += calculator.cpp main.cpp
