######################################################################
# Automatically generated by qmake (3.0) Sun Apr 2 20:04:41 2017
######################################################################

QT += gui widgets

TEMPLATE = app
TARGET = breakoutgame
INCLUDEPATH += .

# Input
HEADERS += ball.h breakout.h brick.h paddle.h
SOURCES += ball.cpp breakout.cpp brick.cpp main.cpp paddle.cpp
