######################################################################
# Automatically generated by qmake (3.0) Sun Apr 2 20:24:12 2017
######################################################################

QT += gui widgets

TEMPLATE = app
TARGET = transparent_rectangles
INCLUDEPATH += .

# Input
HEADERS += transparent_rectangles.h
SOURCES += main.cpp transparent_rectangles.cpp
