######################################################################
# Automatically generated by qmake (3.0) Sun Mar 12 17:26:17 2017
######################################################################

QT += widgets

TEMPLATE = app
TARGET = QComboBox
INCLUDEPATH += .

# Input
HEADERS += combobox.h
SOURCES += combobox.cpp main.cpp
