######################################################################
# Automatically generated by qmake (3.0) Mon Feb 27 20:40:37 2017
######################################################################

TEMPLATE = app
TARGET = curdatetime
INCLUDEPATH += .

# Input
SOURCES += curdatetime.cpp
