######################################################################
# Automatically generated by qmake (3.0) Mon Feb 27 21:13:27 2017
######################################################################

TEMPLATE = app
TARGET = permissions
INCLUDEPATH += .

# Input
SOURCES += permissions.cpp
