######################################################################
# Automatically generated by qmake (3.0) Mon Feb 27 20:21:01 2017
######################################################################

TEMPLATE = app
TARGET = mylist
INCLUDEPATH += .

# Input
SOURCES += mylist.cpp
