######################################################################
# Automatically generated by qmake (3.0) Mon Feb 27 21:31:14 2017
######################################################################

QT += gui widgets

TEMPLATE = app
TARGET = tooltip
INCLUDEPATH += .

# Input
SOURCES += tooltip.cpp
