######################################################################
# Automatically generated by qmake (3.0) Mon Feb 27 23:39:33 2017
######################################################################

QT += gui widgets

TEMPLATE = app
TARGET = cursors
INCLUDEPATH += .

# Input
SOURCES += cursors.cpp
