######################################################################
# Automatically generated by qmake (3.0) Sun Apr 2 20:16:12 2017
######################################################################

QT += gui widgets

TEMPLATE = app
TARGET = colours
INCLUDEPATH += .

# Input
HEADERS += colours.h
SOURCES += colours.cpp main.cpp
