######################################################################
# Automatically generated by qmake (3.0) Sun Mar 12 18:24:11 2017
######################################################################

QT += gui widgets

TEMPLATE = app
TARGET = QCheckBox
INCLUDEPATH += .

# Input
HEADERS += checkbox.h
SOURCES += checkbox.cpp main.cpp
