######################################################################
# Automatically generated by qmake (3.0) Mon Feb 27 21:16:48 2017
######################################################################

TEMPLATE = app
TARGET = special_paths
INCLUDEPATH += .

# Input
SOURCES += special_paths.cpp
