######################################################################
# Automatically generated by qmake (3.0) Mon Feb 27 23:43:05 2017
######################################################################

QT += gui widgets

TEMPLATE = app
TARGET = pushbutton
INCLUDEPATH += .

# Input
SOURCES += pushbutton.cpp
