######################################################################
# Automatically generated by qmake (3.0) Mon Feb 27 21:17:49 2017
######################################################################

TEMPLATE = app
TARGET = write2file
INCLUDEPATH += .

# Input
SOURCES += write2file.cpp
