######################################################################
# Automatically generated by qmake (3.0) Sun Mar 12 18:35:20 2017
######################################################################

QT += gui widgets

TEMPLATE = app
TARGET = QProgressBar
INCLUDEPATH += .

# Input
HEADERS += progressbar.h
SOURCES += main.cpp progressbar.cpp
