######################################################################
# Automatically generated by qmake (3.0) Sun Mar 5 13:18:01 2017
######################################################################

QT += gui widgets

TEMPLATE = app
TARGET = Timer
INCLUDEPATH += .

# Input
HEADERS += timer.h
SOURCES += main.cpp timer.cpp
