######################################################################
# Automatically generated by qmake (3.0) Tue Feb 28 21:03:46 2017
######################################################################

QT += gui widgets

TEMPLATE = app
TARGET = checkable_menu
INCLUDEPATH += .

# Input
HEADERS += checkable.h
SOURCES += checkable.cpp main.cpp
