######################################################################
# Automatically generated by qmake (3.0) Sun Mar 5 13:16:00 2017
######################################################################

QT += gui widgets

TEMPLATE = app
TARGET = QMoveEvent
INCLUDEPATH += .

# Input
HEADERS += move.h
SOURCES += main.cpp move.cpp
