######################################################################
# Automatically generated by qmake (3.0) Sun Mar 5 13:13:06 2017
######################################################################

QT += gui widgets

TEMPLATE = app
TARGET = Disconnecting
INCLUDEPATH += .

# Input
HEADERS += disconnect.h
SOURCES += disconnect.cpp main.cpp
