######################################################################
# Automatically generated by qmake (3.0) Tue Feb 21 22:20:31 2017
######################################################################

TEMPLATE = app
TARGET = right_align
INCLUDEPATH += .

# Input
SOURCES += right_align.cpp
