######################################################################
# Automatically generated by qmake (3.0) Mon Feb 27 21:13:53 2017
######################################################################

TEMPLATE = app
TARGET = read_file
INCLUDEPATH += .

# Input
SOURCES += read_file.cpp
