######################################################################
# Automatically generated by qmake (3.0) Mon Feb 27 21:00:58 2017
######################################################################

TEMPLATE = app
TARGET = unixepoch
INCLUDEPATH += .

# Input
SOURCES += unixepoch.cpp
