######################################################################
# Automatically generated by qmake (3.0) Tue Feb 21 22:18:32 2017
######################################################################

TEMPLATE = app
TARGET = modify
INCLUDEPATH += .

# Input
SOURCES += modify.cpp
