######################################################################
# Automatically generated by qmake (3.0) Mon Feb 27 20:46:29 2017
######################################################################

TEMPLATE = app
TARGET = datetime
INCLUDEPATH += .

# Input
SOURCES += datetime.cpp
