######################################################################
# Automatically generated by qmake (3.0) Tue Feb 21 21:48:35 2017
######################################################################

TEMPLATE = app
TARGET = building
INCLUDEPATH += .

# Input
SOURCES += building.cpp

QT -= hui