######################################################################
# Automatically generated by qmake (3.0) Tue Feb 21 22:07:40 2017
######################################################################

TEMPLATE = app
TARGET = comparing
INCLUDEPATH += .

# Input
SOURCES += comparing.cpp
