######################################################################
# Automatically generated by qmake (3.0) Sun Apr 2 20:21:38 2017
######################################################################

QT += gui widgets

TEMPLATE = app
TARGET = radial_gradient
INCLUDEPATH += .

# Input
HEADERS += radial_gradient.h
SOURCES += main.cpp radial_gradient.cpp
