######################################################################
# Automatically generated by qmake (3.0) Mon Feb 27 20:45:19 2017
######################################################################

TEMPLATE = app
TARGET = dateformats
INCLUDEPATH += .

# Input
SOURCES += dateformats.cpp
