######################################################################
# Automatically generated by qmake (3.0) Mon Feb 27 20:26:29 2017
######################################################################

TEMPLATE = app
TARGET = myset
INCLUDEPATH += .

# Input
SOURCES += myset.cpp
