######################################################################
# Automatically generated by qmake (3.0) Sun Mar 5 13:14:08 2017
######################################################################

QT += gui widgets

TEMPLATE = app
TARGET = KeyPress
INCLUDEPATH += .

# Input
HEADERS += keypress.h
SOURCES += keypress.cpp main.cpp
