######################################################################
# Automatically generated by qmake (3.0) Mon Feb 27 21:02:26 2017
######################################################################

TEMPLATE = app
TARGET = utclocal
INCLUDEPATH += .

# Input
SOURCES += utclocal.cpp
