######################################################################
# Automatically generated by qmake (3.0) Mon Feb 27 21:05:34 2017
######################################################################

TEMPLATE = app
TARGET = weekday
INCLUDEPATH += .

# Input
SOURCES += weekday.cpp
