######################################################################
# Automatically generated by qmake (3.0) Sun Mar 12 18:03:35 2017
######################################################################

QT += gui widgets

TEMPLATE = app
TARGET = QLabel
INCLUDEPATH += .

# Input
HEADERS += label.h
SOURCES += label.cpp main.cpp
