######################################################################
# Automatically generated by qmake (3.0) Sun Mar 12 18:40:31 2017
######################################################################

QT += gui widgets

TEMPLATE = app
TARGET = QTableWidget
INCLUDEPATH += .

# Input
HEADERS += table.h
SOURCES += main.cpp table.cpp
