######################################################################
# Automatically generated by qmake (3.0) Tue Feb 21 21:38:24 2017
######################################################################

TEMPLATE = app
TARGET = access
INCLUDEPATH += .

# Input
SOURCES += access.cpp

QT -= gui