######################################################################
# Automatically generated by qmake (3.0) Tue Feb 21 21:35:23 2017
######################################################################

TEMPLATE = app
TARGET = init
INCLUDEPATH += .

# Input
SOURCES += init.cpp

QT -= gui
