######################################################################
# Automatically generated by qmake (3.0) Tue Feb 21 21:59:39 2017
######################################################################

TEMPLATE = app
TARGET = substring
INCLUDEPATH += .

# Input
SOURCES += substring.cpp

QT -= gui