######################################################################
# Automatically generated by qmake (3.0) Sun Apr 2 20:20:00 2017
######################################################################

QT += gui widgets

TEMPLATE = app
TARGET = patterns
INCLUDEPATH += .

# Input
HEADERS += patterns.h
SOURCES += main.cpp patterns.cpp
